question: monday
solution: 月曜日

---

question: tuesday
solution: 火曜日

---

question: wednesday
solution: 水曜日

---

question: thursday
solution: 木曜日

---

question: friday
solution: 金曜日

---

question: saturday
solution: 土曜日

---

question: sunday
solution: 日曜日

---

question: 今
solution: いま

---

question: 来週
solution: らいしゆう

